using System.ComponentModel.DataAnnotations;
using Puod.Services.User.Models;

namespace Puod.Services.User.DTOs;

public record CompanyDetailResponse(
    long Id,
    string Name,
    string? CompanyName,
    string Slug,
    long? ClientId,
    string? ClientName,
    bool InheritFromClient,
    bool InheritBasicInfo,
    bool InheritLogo,
    bool InheritContact,
    bool InheritAddress,
    bool InheritDetails,
    bool InheritAuthentication,
    bool InheritIntegrations,
    SubscriptionTier Tier,
    bool IsActive,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    int UserCount,
    string? LogoUrl,
    string? TaxId,
    string? Website,
    string? Email,
    string? Phone,
    string? Address,
    string? City,
    string? State,
    string? Country,
    string? PostalCode,
    string? Description,
    string? Industry,
    int? EmployeeCount,
    DateTime? FoundedDate);

public record CompanyListResponse(
    long Id,
    string Name,
    string? CompanyName,
    string Slug,
    long? ClientId,
    string? ClientName,
    bool InheritFromClient,
    SubscriptionTier Tier,
    bool IsActive,
    DateTime CreatedAt,
    int UserCount,
    string? LogoUrl,
    string? Country,
    string? Industry);

public record CompanyCreateRequest(
    [Required] string Name,
    string? CompanyName,
    [Required] long ClientId,
    bool InheritFromClient = true,
    bool InheritBasicInfo = false,
    bool InheritLogo = false,
    bool InheritContact = false,
    bool InheritAddress = false,
    bool InheritDetails = false,
    bool InheritAuthentication = false,
    bool InheritIntegrations = false,
    // Individual info fields - only used if corresponding Inherit* is false
    string? LogoUrl = null,
    string? TaxId = null,
    string? Website = null,
    string? Email = null,
    string? Phone = null,
    string? Address = null,
    string? City = null,
    string? State = null,
    string? Country = null,
    string? PostalCode = null,
    string? Description = null,
    string? Industry = null,
    int? EmployeeCount = null,
    DateTime? FoundedDate = null);

public record CompanyUpdateRequest(
    [Required] string Name,
    string? CompanyName,
    bool InheritFromClient,
    bool InheritBasicInfo,
    bool InheritLogo,
    bool InheritContact,
    bool InheritAddress,
    bool InheritDetails,
    bool InheritAuthentication,
    bool InheritIntegrations,
    bool IsActive,
    // Individual info fields - only used if corresponding Inherit* is false
    string? LogoUrl = null,
    string? TaxId = null,
    string? Website = null,
    string? Email = null,
    string? Phone = null,
    string? Address = null,
    string? City = null,
    string? State = null,
    string? Country = null,
    string? PostalCode = null,
    string? Description = null,
    string? Industry = null,
    int? EmployeeCount = null,
    DateTime? FoundedDate = null);
